---
# file: roles/virt-env-ospd/tasks/config.yml
- name: Propagate director version from Hypervisor (needed for vbmc setup on hypervisor)
  set_fact:
    virt_env_ospd_director_version: "{{ hostvars[groups['hypervisor'][0]]['virt_env_ospd_director_version'] }}"
    instackenv_pm_type: "{{ hostvars[groups['hypervisor'][0]]['instackenv_pm_type'] }}"

- name: Set undercloud hostname
  hostname:
    name={{ virt_env_ospd_undercloud_hostname.split('.')[0] }}

- fail: msg="instackenv_pm_type must be either 'pxe_ssh' or 'pxe_ipmitool' (OSP12)"
  when: instackenv_pm_type not in ['pxe_ssh','pxe_ipmitool']

- fail: msg="instackenv_pm_type var on undercloud must match value on hypervisor. Check your vars!!"
  when: instackenv_pm_type != hostvars[groups['hypervisor'][0]]['instackenv_pm_type']

- name: "Debug instackenv_pm_type"
  debug:
    msg: "instackenv_pm_type={{ instackenv_pm_type }}, HVM={{ hostvars[groups['hypervisor'][0]]['instackenv_pm_type'] }}"

- name: "Debug OSP Director version"
  debug:
    msg: "virt_env_ospd_director_version={{ virt_env_ospd_director_version }}, HVM={{ hostvars[groups['hypervisor'][0]]['virt_env_ospd_director_version'] }}"

- name: Find my own IP on 192.168.122.x/24
  shell: |
    hostname -I|xargs -n1|grep '192\.168\.122\.'
  register: undercloud_dhcp_ip

- name: Configuring Undercloud's /etc/hosts file
  lineinfile:
    dest=/etc/hosts
    regexp='.* {{ virt_env_ospd_undercloud_hostname }} {{ virt_env_ospd_undercloud_hostname.split('.')[0] }}'
    line='10.20.0.2 {{ virt_env_ospd_undercloud_hostname }} {{ virt_env_ospd_undercloud_hostname.split('.')[0] }}'
    #line='{{ undercloud_dhcp_ip.stdout }} {{ virt_env_ospd_undercloud_hostname }} {{ virt_env_ospd_undercloud_hostname.split('.')[0] }}'

- include: subscribtion.yml
  when: virt_env_ospd_rhos_release is defined and
        not virt_env_ospd_rhos_release

- include: repos.yml
  when: virt_env_ospd_rhos_release is defined and
        not virt_env_ospd_rhos_release

# We cannot use Ansible yum module because when there is no subcription
# yum complains about missing repo... Ansible rpm module doesn't exist
- name: Installing rhos-release package
  command:
    rpm -Uh http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm --force
  when: virt_env_ospd_rhos_release is defined and
        virt_env_ospd_rhos_release

- name: Set the OSP-director version
  command:
    rhos-release -P {{ virt_env_ospd_director_version }}
  when: virt_env_ospd_rhos_release is defined and
        virt_env_ospd_rhos_release

# The package module doesn't support yet the global update
- name: Updating system with latest packages
  yum:
    name=*
    state=latest
    update_cache=yes

- name: Installing undercloud pre-requisites
  yum:
    name={{ item }}
    state=present
  with_items: "{{ virt_env_ospd_undercloud_packages }}"

- name: Creating directories in stack's home
  file:
    path=/home/stack/{{ item }}
    state=directory
    owner=stack
    group=stack
  with_items:
    - images
    - "{{ virt_env_ospd_undercloud_hostname }}/samples"
