---
# file: roles/virt-env-ospd/tasks/hypervisor.yml
- name: Checking if VM exists (ignore the error)
  virt:
    name={{ virt_env_ospd_undercloud.name }}
    command=status
  register: vm
  ignore_errors: true

- name: Creating QCOW2 file for Ceph
  command:
    qemu-img create \
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-{{ item }}-boot.{{ virt_env_ospd_format }} {{ virt_env_ospd_ceph.disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-{{ item }}-boot.{{ virt_env_ospd_format }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_ceph.vm_count | int }}
  when: virt_env_ospd_ceph is defined

- name: Creating QCOW2 file for Swift
  command:
    qemu-img create \
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_swift.name }}-{{ item }}-boot.{{ virt_env_ospd_format }} {{ virt_env_ospd_swift.disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_swift.name }}-{{ item }}-boot.{{ virt_env_ospd_format }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_swift.vm_count | int }}
  when: virt_env_ospd_swift is defined

- name: Creating QCOW2 file for controller
  command:
    qemu-img create \
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_control.name }}-{{ item }}-boot.{{ virt_env_ospd_format }} {{ virt_env_ospd_control.disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_control.name }}-{{ item }}-boot.{{ virt_env_ospd_format }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_control.vm_count | int }}
  when: virt_env_ospd_control is defined

- name: Creating QCOW2 file for compute
  command:
    qemu-img create \
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-{{ item }}-boot.{{ virt_env_ospd_format }} {{ virt_env_ospd_compute.disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-{{ item }}-boot.{{ virt_env_ospd_format }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_compute.vm_count | int }}
  when: virt_env_ospd_compute is defined

- name: Creating Ceph virtual machines
  virt:
    name={{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-{{ item }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/ceph.xml.j2') }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_ceph.vm_count | int }}
  when: virt_env_ospd_ceph is defined

- name: Creating Swift virtual machines
  virt:
    name={{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_swift.name }}-{{ item }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/swift.xml.j2') }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_swift.vm_count | int }}
  when: virt_env_ospd_swift is defined

- name: Creating controller virtual machines
  virt:
    name={{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_control.name }}-{{ item }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/control.xml.j2') }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_control.vm_count | int }}
  when: virt_env_ospd_control is defined

- name: Creating compute virtual machines
  virt:
    name={{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-{{ item }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/compute.xml.j2') }}
  with_sequence:
    start=0
    count={{ virt_env_ospd_compute.vm_count | int }}
  when: virt_env_ospd_compute is defined

- name: Creating extra QCOW2 file(s) for Ceph
  shell: |
    if [ -f {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-ceph-{{ item.1 }}-extra-{{ item.0.name }}.{{ item.0.format }} ]; then
      echo "Disk already OK"
    else
    qemu-img create -f {{ item.0.format }} {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-ceph-{{ item.1 }}-extra-{{ item.0.name }}.{{ item.0.format }} {{ item.0.size }}
    virsh attach-disk {{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-{{item.1}} \
      --source {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-{{item.1}}-extra-{{ item.0.name }}.{{ item.0.format }} \
      --target {{ item.0.name }} \
      --targetbus {{ item.0.bus }} \
      --cache {{ virt_env_ospd_cache_mode }} \
      --subdriver {{ item.0.format }} \
      --persistent
    fi
  with_nested:
  - "{{ virt_env_ospd_ceph_extra_disk }}"
  - "{{lookup('sequence', 'start=0 count={{ virt_env_ospd_ceph.vm_count }}', wantlist=True)}}"
  when: "virt_env_ospd_ceph_extra_disk is defined and {{virt_env_ospd_ceph_extra_disk | length | int != 0}}"
  ignore_errors: True

- name: Creating extra QCOW2 file(s) for Swift
  shell: |
    if [ -f {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-swift-{{ item.1 }}-extra-{{ item.0.name }}.{{ item.0.format }} ]; then
      echo "Disk already OK"
    else
    qemu-img create -f {{ item.0.format }} {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-swift-{{ item.1 }}-extra-{{ item.0.name }}.{{ item.0.format }} {{ item.0.size }}
    virsh attach-disk {{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_swift.name }}-{{item.1}} \
      --source {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_swift.name }}-{{item.1}}-extra-{{ item.0.name }}.{{ item.0.format }} \
      --target {{ item.0.name }} \
      --targetbus {{ item.0.bus }} \
      --cache {{ virt_env_ospd_cache_mode }} \
      --subdriver {{ item.0.format }} \
      --persistent
    fi
  with_nested:
  - "{{ virt_env_ospd_swift_extra_disk }}"
  - "{{lookup('sequence', 'start=0 count={{ virt_env_ospd_swift.vm_count }}', wantlist=True)}}"
  when: "virt_env_ospd_swift_extra_disk is defined and {{virt_env_ospd_swift_extra_disk | length | int != 0}}"
  ignore_errors: True

- name: Creating extra QCOW2 file(s) for Computes
  shell: |
    if [ -f {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-compute-{{ item.1 }}-extra-{{ item.0.name }}.{{ item.0.format }} ]; then
      echo "Disk already OK"
    else
    qemu-img create -f {{ item.0.format }} {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-compute-{{ item.1 }}-extra-{{ item.0.name }}.{{ item.0.format }} {{ item.0.size }}
    virsh attach-disk {{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-{{item.1}} \
      --source {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-{{item.1}}-extra-{{ item.0.name }}.{{ item.0.format }} \
      --target {{ item.0.name }} \
      --targetbus {{ item.0.bus }} \
      --cache {{ virt_env_ospd_cache_mode }} \
      --subdriver {{ item.0.format }} \
      --persistent
    fi
  with_nested:
  - "{{ virt_env_ospd_compute_extra_disk }}"
  - "{{lookup('sequence', 'start=0 count={{ virt_env_ospd_compute.vm_count }}', wantlist=True)}}"
  when: "virt_env_ospd_compute_extra_disk is defined and {{virt_env_ospd_compute_extra_disk | length | int != 0}}"
  ignore_errors: True

