---
# file: roles/virt-env-ospd/tasks/instackenv.yml
- name: set_fact on instackenv_pm_type
  set_fact:
    instackenv_pm_type: "{{ hostvars[groups['hypervisor'][0]]['instackenv_pm_type'] }}"
    vbmc_user: "{{ hostvars[groups['hypervisor'][0]]['vbmc_user'] }}"
    vbmc_password: "{{ hostvars[groups['hypervisor'][0]]['vbmc_password'] }}"
    vbmc_port: "{{ hostvars[groups['hypervisor'][0]]['vbmc_port'] }}"

# Only to this for osp11 and below
- name: Generating the instackenv.json file
  template:
    src=home/stack/instackenv.json.j2
    dest=/home/stack/instackenv.json
    owner=stack
    group=stack
    mode=0640
    force=yes
  when: virt_env_ospd_director_version in ['8-director', '9-director', '10-director', '11-director', '12-director', '13-director']

- name: Validating instackenv.json file (OSP-d 8 only)
  shell:
    source ~/stackrc ;
    openstack baremetal instackenv validate
  become: true
  become_user: stack
  when: virt_env_ospd_director_version in ['8-director', '9-director', '10-director', '11-director', '12-director', '13-director']
        and virt_env_ospd_conf_undercloud_for_me

- name: Importing instackenv.json file
  shell:
    source ~/stackrc ;
    openstack baremetal import --json ~/instackenv.json
  become: true
  become_user: stack
  when: virt_env_ospd_director_version in ['8-director', '9-director', '10-director', '11-director', '12-director', '13-director']
        and virt_env_ospd_conf_undercloud_for_me
