---
# file: roles/virt-env-ospd/tasks/instackenv.yml
- name: set some more facts
  set_fact:
    ironic_ssh_priv_key: '/home/stack/.ssh/ironic_id_rsa'
    ironic_ssh_pub_key: '/home/stack/.ssh/ironic_id_rsa.pub'
    ironic_ssh_auth_list: '/home/stack/.ssh/authorized_keys'

- name: Load ironic's private SSH key
  shell:
    sed ':a;N;$!ba;s/\n/\\n/g' {{ ironic_ssh_priv_key }}
  register: ironic_key

- name: Set another fact
  set_fact:
    virt_env_ospd_ssh_prv: "{{ ironic_key.stdout }}"

- name: Generating the instackenv.json file
  template:
    src=home/stack/instackenv.json.j2
    dest=/home/stack/instackenv.json
    owner=stack
    group=stack
    mode=0640

- name: Validating instackenv.json file (OSP-d 8 only)
  shell:
    source ~/stackrc ;
    openstack baremetal instackenv validate
  become: true
  become_user: stack
  when: virt_env_ospd_director_version is defined and
        virt_env_ospd_director_version == '8-director' and
        virt_env_ospd_conf_undercloud_for_me is defined
        and virt_env_ospd_conf_undercloud_for_me

- name: Importing instackenv.json file
  shell:
    source ~/stackrc ;
    openstack baremetal import --json ~/instackenv.json
  become: true
  become_user: stack
  when: virt_env_ospd_director_version is defined and
        virt_env_ospd_director_version == '8-director' and
        virt_env_ospd_conf_undercloud_for_me is defined
        and virt_env_ospd_conf_undercloud_for_me
