---
# file: roles/virs-env-ospd/tasks/ironic.yml
- name: Configuring Ironic nodes
  shell:
    source ~/stackrc ;
    openstack baremetal configure boot
  become: true
  become_user: stack
  when: virt_env_ospd_ironic_introspection is defined and
        virt_env_ospd_ironic_introspection and
        virt_env_ospd_conf_undercloud_for_me is defined
        and virt_env_ospd_conf_undercloud_for_me

- name: Starting Ironic introspection
  shell:
    source ~/stackrc ;
    openstack baremetal introspection bulk start
  become: true
  become_user: stack
  when: virt_env_ospd_ironic_introspection is defined and
        virt_env_ospd_ironic_introspection and
        virt_env_ospd_conf_undercloud_for_me is defined
        and virt_env_ospd_conf_undercloud_for_me

- name: Generating ironic-profiling script (ironic cli)
  when: virt_env_ospd_director_version in ['8-director', '9-director', '10-director']
  template:
    src=home/stack/ironic-profiling.sh.j2
    dest=/home/stack/ironic-profiling.sh
    owner=stack
    group=stack
    mode=0755

- name: Generating ironic-profiling script (openstack baremetal cli)
  when: virt_env_ospd_director_version in ['11-director', '12-director', '13-director', '15-director', '16-director']
  template:
    src=home/stack/ironic-profiling-v2.sh.j2
    dest=/home/stack/ironic-profiling.sh
    owner=stack
    group=stack
    mode=0755

- name: Tagging profile on Ironic nodes
  shell:
    source ~/stackrc ;
    /home/stack/ironic-profiling.sh
  become: true
  become_user: stack
  when: virt_env_ospd_ironic_introspection is defined and
        virt_env_ospd_ironic_introspection and
        virt_env_ospd_conf_undercloud_for_me is defined
        and virt_env_ospd_conf_undercloud_for_me
