---
# file: roles/virt-env-ospd/tasks/krynn.yml
- name: "Debug hostname"
  debug:
    msg: "ansible_hostname={{ ansible_hostname }}, dns_domain={{ ansible_dns.domain }}"

- name: "Debug OSP Director guest name"
  debug:
    msg: "virt_env_ospd_undercloud.name = {{ virt_env_ospd_undercloud.name  }}"

- name: Copy RHEL 7.y image to destination
  copy:
    src=/net/imladris/export/home/raistlin/World/Vincent/Projects/www.redhat.com/Instack/rhel-7.5-guest.x86_64.qcow2
    dest={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
    owner=root
    group=root
    mode=0644
    force=no
  when: ansible_dns.domain == "lasthome.solace.krynn"
