---
# file: roles/virt-env-ospd/tasks/krynn_hypervisor.yml
- name: "Debug hostname"
  debug:
    msg: "ansible_hostname={{ ansible_hostname }}, dns_domain={{ ansible_dns.domain }}"

- name: "Debug OSP Director guest name"
  debug:
    msg: "virt_env_ospd_undercloud.name = {{ virt_env_ospd_undercloud.name  }}"

# proxy config for krynn
- name: Enforce Proxy config in /etc/yum.conf
  lineinfile: dest=/etc/yum.conf
              regexp="^proxy="
              state=present
              create=yes
              line="proxy=http://{{ http_proxy_host }}:{{ http_proxy_port }}"
  when:
    - ansible_distribution == 'RedHat'

- name: Enforce Proxy config in /etc/rhsm/rhsm.conf (proxy_hostname)
  lineinfile: dest=/etc/rhsm/rhsm.conf
              regexp="^proxy_hostname ="
              state=present
              create=yes
              line="proxy_hostname = {{ http_proxy_host }}"
  when:
    - ansible_distribution == 'RedHat'

- name: Enforce Proxy config in /etc/rhsm/rhsm.conf (proxy_port)
  lineinfile: dest=/etc/rhsm/rhsm.conf
              regexp="^proxy_port ="
              state=present
              create=yes
              line="proxy_port = {{ http_proxy_port }}"
  when:
    - ansible_distribution == 'RedHat'

