---
# file: roles/virt-env-ospd/tasks/krynn_hypervisor.yml
- name: "Debug hostname / dns domain"
  debug:
    msg: "ansible_hostname={{ ansible_hostname }}, dns_domain={{ ansible_domain }}"

- name: "Debug OSP Director guest name"
  debug:
    msg: "virt_env_ospd_undercloud.name = {{ virt_env_ospd_undercloud.name  }}"

# Fixed on vxfs, see: https://github.com/ansible/ansible/issues/29728
#- name: Copy RHEL 7.y image to destination
#  copy:
#    src=/net/imladris//export/home/raistlin/World/Vincent/Code/GIT/Instack/rhel-7-guest.x86_64.qcow2
#    dest={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
#    owner=qemu
#    group=qemu
#    mode=0644
#  when:
#    - virt_env_ospd_refresh_guest_image
#    - virt_env_ospd_director_version in ['8-director', '9-director', '10-director', '11-director', '12-director', '13-director']

#- name: Copy RHEL 8.y image to destination
#  copy:
#    src=/net/imladris//export/home/raistlin/World/Vincent/Code/GIT/Instack/rhel-8-guest.x86_64.qcow2
#    dest={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
#    owner=qemu
#    group=qemu
#    mode=0644
#  when:
#    - virt_env_ospd_refresh_guest_image
#    - virt_env_ospd_director_version in ['15-director', '16-director']

# Back to rsync in case the file is too big for sftp to handle (>4g)

- name: Copy RHEL 7.y image to destination
  become: true
  shell: |
    /usr/bin/rsync -upt /net/imladris//export/home/raistlin/World/Vincent/Code/GIT/Instack/rhel-7-guest.x86_64.qcow2 \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
    chown qemu:qemu {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
  when:
    - virt_env_ospd_refresh_guest_image
    - virt_env_ospd_director_version in ['8-director', '9-director', '10-director', '11-director', '12-director', '13-director']

- name: Copy RHEL 8.y image to destination
  become: true
  shell: |
    /usr/bin/rsync -upt /net/imladris//export/home/raistlin/World/Vincent/Code/GIT/Instack/rhel-8-guest.x86_64.qcow2 \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
    chown qemu:qemu {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
  when:
    - virt_env_ospd_refresh_guest_image
    - virt_env_ospd_director_version in ['15-director', '16-director']
