---
# file: roles/virt-env-ospd/tasks/krynn_hypervisor.yml
- name: "Debug hostname / dns domain"
  debug:
    msg: "ansible_hostname={{ ansible_hostname }}, dns_domain={{ ansible_domain }}"

- name: "Debug OSP Director KVM guest name"
  debug:
    msg: "virt_env_ospd_undercloud.name = {{ virt_env_ospd_undercloud.name  }}"

- name: "Debug OSP Director hostname"
  debug:
    msg: "virt_env_ospd_undercloud_hostname = {{ virt_env_ospd_undercloud_hostname  }}"

# proxy config for krynn
- name: Enforce Proxy config in /etc/yum.conf
  lineinfile: dest=/etc/yum.conf
              regexp="^proxy="
              state=present
              create=yes
              line="proxy=http://{{ http_proxy_host }}:{{ http_proxy_port }}"
  when: ansible_domain == "lasthome.solace.krynn"

- name: Enforce Proxy config in /etc/rhsm/rhsm.conf (proxy_hostname)
  lineinfile: dest=/etc/rhsm/rhsm.conf
              regexp="^proxy_hostname ="
              state=present
              create=yes
              line="proxy_hostname = {{ http_proxy_host }}"
  when: ansible_domain == "lasthome.solace.krynn"

- name: Enforce Proxy config in /etc/rhsm/rhsm.conf (proxy_port)
  lineinfile: dest=/etc/rhsm/rhsm.conf
              regexp="^proxy_port ="
              state=present
              create=yes
              line="proxy_port = {{ http_proxy_port }}"
  when: ansible_domain == "lasthome.solace.krynn"

- name: discover target external IP on bond2
  shell: |
    host -4 {{ virt_env_ospd_undercloud_hostname }}|awk '{ print $4}'
    #host -4 $(hostname -f)|awk '{ print $4}'
  register: undercloud_bond2_ip

- name: rebuild /etc/sysconfig/network-scripts/ifcfg-bond2 on Undercloud
  template:
    src=etc/sysconfig/network-scripts/ifcfg-bond2
    dest=/etc/sysconfig/network-scripts/ifcfg-bond2
    force=yes
  with_items:
    - "{{ undercloud_bond2_ip.stdout }}"

- name: reconfigure bond2 on undercloud VM
  shell: |
    /usr/sbin/ifdown bond2
    /usr/sbin/ifup bond2
