---
# file: roles/virt-env-ospd/tasks/main.yml
- include_vars: 7-director.yml
  when: virt_env_ospd_director_version == '7-director'

- include_vars: 8-director.yml
  when: virt_env_ospd_director_version == '8-director'

- include_vars: 10-director.yml
  when: virt_env_ospd_director_version == '10-director'

- include: prepare.yml
  when: "'hypervisor' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-prepare ]

- include: hypervisor.yml
  when: "'hypervisor' in group_names and
        virt_env_ospd_hypervisor is defined and
        virt_env_ospd_hypervisor"
  tags:
    [ virt-env-ospd, virt-env-ospd-hypervisor ]

- include: masquerade.yml
  when: "'hypervisor' in group_names and
        virt_env_ospd_hypervisor is defined and
        virt_env_ospd_hypervisor"
  tags:
    [ virt-env-ospd, virt-env-ospd-masquerade ]

- include: virtualbmc.yml
  when: "'hypervisor' in group_names and
        instackenv_pm_type == 'pxe_ipmitool'"
  tags:
    [ virt-env-ospd, virt-env-ospd-hypervisor, virt-env-ospd-virtualbmc ]

- include: undercloud-vm.yml
  when: "'hypervisor' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-undercloud ]

- include: config.yml
  when: "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-config ]

- include: install.yml
  when: "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-install ]

- include: instackenv.yml
  when: "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-instackenv ]

- include: ironic.yml
  when: "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-ironic ]

- include: flavor.yml
  when: "'undercloud' in group_names and
        virt_env_ospd_conf_undercloud_for_me is defined
        and virt_env_ospd_conf_undercloud_for_me"
  tags:
    [ virt-env-ospd, virt-env-ospd-flavor ]

- include: templates.yml
  when: "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-template ]

- include: tools.yml
  when: "'undercloud' in group_names and
        virt_env_ospd_rcip_tools is defined and
        virt_env_ospd_rcip_tools"
  tags:
    [ virt-env-ospd, virt-env-ospd-tool ]
