---
# file: roles/virt-env-ospd/tasks/main.yml
- name: Include OSP version-specific variables.. ( {{ virt_env_ospd_director_version }} )
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ virt_env_ospd_director_version }}.yml"
    - "default.yml"

# Krynn-specific
- include: krynn_hypervisor.yml
  when:
    - "'hypervisor' in group_names"
    - ansible_domain == 'lasthome.solace.krynn'
  tags:
    [ virt-env-hypervisor, virt-env-ospd-site-specific ]

- include: prepare.yml
  when:
    - "'hypervisor' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-prepare ]

- include: hypervisor.yml
  when:
    - "'hypervisor' in group_names"
    - virt_env_ospd_hypervisor is defined
    - virt_env_ospd_hypervisor == "true"
  tags:
    [ virt-env-ospd, virt-env-ospd-hypervisor ]

- include: masquerade.yml
  when:
    - "'hypervisor' in group_names"
    - virt_env_ospd_hypervisor is defined
    - virt_env_ospd_hypervisor == "true"
  tags:
    [ virt-env-ospd, virt-env-ospd-masquerade ]

- include: virtualbmc.yml
  when:
    - "'hypervisor' in group_names"
    - instackenv_pm_type == 'pxe_ipmitool'
  tags:
    [ virt-env-ospd, virt-env-ospd-hypervisor, virt-env-ospd-virtualbmc ]

- include: undercloud-vm.yml
  when:
    - "'hypervisor' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-undercloud ]

# Krynn-specific (Undercloud)
- include: krynn_undercloud.yml
  when:
    - "'undercloud' in group_names"
    - ansible_domain == 'lasthome.solace.krynn'
  tags:
    [ virt-env-ospd, virt-env-ospd-site-specific ]

- include: config.yml
  when:
    - "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-config ]

- include: install.yml
  when:
    - "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-install ]

- include: instackenv.yml
  when:
    - "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-instackenv ]

- include: ironic.yml
  when:
    - "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-ironic ]

- include: flavor.yml
  when:
    - "'undercloud' in group_names"
    - virt_env_ospd_conf_undercloud_for_me is defined
    - virt_env_ospd_conf_undercloud_for_me == "true"
  tags:
    [ virt-env-ospd, virt-env-ospd-flavor ]

- include: templates.yml
  when:
    - "'undercloud' in group_names"
  tags:
    [ virt-env-ospd, virt-env-ospd-template ]

- include: tools.yml
  when:
    - "'undercloud' in group_names"
    - virt_env_ospd_git_tools is defined
    - virt_env_ospd_git_tools == "true"
  tags:
    [ virt-env-ospd, virt-env-ospd-tool ]
