---
# file: roles/virt-env-ospd/tasks/subcription.yml
- name: Unsubscribing and unregistering the server to RHSM
  shell:
    /usr/bin/subscription-manager unsubscribe --all;
    /usr/bin/subscription-manager unregister;
    /usr/bin/subscription-manager clean
  when: virt_env_ospd_rhn_unsubscribe is defined and
        virt_env_ospd_rhn_unsubscribe

- name: Registering the server to RHSM
  redhat_subscription:
    username={{ rhn_username }}
    password={{ rhn_password }}
    state=present
  when: virt_env_ospd_rhn_subscribe is defined and
        virt_env_ospd_rhn_subscribe

- name: Subscribing the server to a pool
  shell:
    /usr/bin/subscription-manager subscribe --pool {{ rhn_pool_id }}
  when: virt_env_ospd_rhn_subscribe is defined and
        virt_env_ospd_rhn_subscribe
