---
# file: roles/virt-env-ospd/defaults/main.yml
virt_env_ospd_dir: /var/lib/libvirt
virt_env_ospd_hypervisor: true
virt_env_ospd_tuned: true
virt_env_ospd_git_tools: false
virt_env_ospd_rhn_unsubscribe: false
virt_env_ospd_rhn_subscribe: false
virt_env_ospd_rhos_release: false
virt_env_ospd_disable_repos: false
virt_env_ospd_ironic_introspection: true
virt_env_ospd_director_version: 10-director
virt_env_ospd_vm_name: baremetal
virt_env_ospd_undercloud_hostname: manager.mydomain.lab
virt_env_ospd_neutron_dns: 8.8.8.8
virt_env_ospd_conf_undercloud_for_me: true
vbmc_user: admin
vbmc_password: password
vbmc_port: 6231
vbmc_non_root_user: nobody
virt_env_ospd_bridges:
  - director-pxe
  - director-full
virt_env_ospd_guest_name: rhel-7.4-guest.x86_64.qcow2
# IMAGES
virt_env_ospd_upload_images: false
virt_env_ospd_images_link:
  - http://rhos-release.virt.bos.redhat.com/mburns/latest-7.0-images/deploy-ramdisk-ironic.tar
  - http://rhos-release.virt.bos.redhat.com/mburns/latest-7.0-images/discovery-ramdisk.tar
  - http://rhos-release.virt.bos.redhat.com/mburns/latest-7.0-images/overcloud-full.tar

# INSTACKENV.JSON
instackenv_pm_type: pxe_ssh
instackenv_pm_addr: 192.168.122.1
instackenv_pm_user: root
instackenv_pm_password: "{{ virt_env_ospd_ssh_prv }}"
instackenv_cpu: 4
instackenv_memory: 8192
instackenv_disk: 80
instackenv_arch: x86_64

# UNDERCLOUD VM
virt_env_ospd_undercloud:
  name: undercloud
  disk_size: 40g
  cpu: 8
  mem: 16384
  cloud_init_iso: cloud-init.iso

# CEPH VM
virt_env_ospd_ceph:
  name: ceph
  disk_size: 40g
  cpu: 4
  mem: 4096
  mac: 52:54:00:aa:d3:8
  vm_count: 3
  extra_disk_count: 3

# CEPH EXTRA DISKS
virt_env_ospd_ceph_extra_disk:
  - { name: sdb, size: 10g, format: qcow2, bus: sata }
  - { name: sdc, size: 10g, format: qcow2, bus: sata }
  - { name: sdd, size: 10g, format: qcow2, bus: sata }

# SWIFT VM
virt_env_ospd_swift:
  name: swift
  disk_size: 40g
  cpu: 4
  mem: 4096
  mac: 52:54:00:aa:d3:5
  vm_count: 3
  extra_disk_count: 3

# SWIFT EXTRA DISKS
virt_env_ospd_swift_extra_disk:
  - { name: sdb, size: 10g, format: qcow2, bus: sata }
  - { name: sdc, size: 10g, format: qcow2, bus: sata }
  - { name: sdd, size: 10g, format: qcow2, bus: sata }

# CONTROL VM
virt_env_ospd_control:
  name: control
  disk_size: 40g
  cpu: 4
  mem: 8192
  mac: 52:54:00:aa:d3:6
  vm_count: 3

# COMPUTE VM
virt_env_ospd_compute:
  name: compute
  disk_size: 40g
  cpu: 4
  mem: 4096
  mac: 52:54:00:aa:d3:7
  vm_count: 3

virt_env_ospd_block:

# LIBVIRT
# To get machine types available execute this command:
# /usr/libexec/qemu-kvm -machine help
virt_env_ospd_machine_type: pc-i440fx-rhel7.0.0
virt_env_ospd_libvirt_bridge: virbr0
virt_env_ospd_external_bridge: bond0
virt_env_ospd_libvirt_net_name: default
virt_env_ospd_disk_os_bus: sata

# Because virtio driver doesn't work well with Ironic
# depending of the qemu-kvm version (rhev or not)
# Change it if needed :)
# virt_env_ospd_net_driver_pxe: e1000
virt_env_ospd_net_driver_pxe: virtio

# Some issues during overcloud deployment due to virtio
# network driver (resource create failed)
# Change it if needed :)
virt_env_ospd_net_driver: virtio

# virt_env_ospd_cache_mode: none
# virt_env_ospd_cache_mode: writethrough
virt_env_ospd_cache_mode: writeback
