---
# file: roles/virt-env-ospd/vars/7-director.yml
virt_env_ospd_undercloud_packages:
  - strace
  - tcpdump
  - screen
  - tmux
  - git
  - python-rdomanager-oscplugin
  - libguestfs-tools
  - sysstat
  - sos
  - bash-completion
instackenv_pm_type: pxe_ssh
