---
# file: roles/virt-env-ospd/tasks/hypervisor.yml
- name: Creating QCOW2 file for Ceph
  command:
    qemu-img create \
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-os-{{ item }}.{{ virt_env_ospd_format }} {{ virt_env_ospd_ceph.disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-os-{{ item }}.{{ virt_env_ospd_format }}
  with_sequence:
    start=1
    end={{ virt_env_ospd_ceph.vm_count }}
  when: virt_env_ospd_ceph is defined

- name: Creating QCOW2 file for controller
  command:
    qemu-img create \
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_control.name }}-os-{{ item }}.{{ virt_env_ospd_format }} {{ virt_env_ospd_control.disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_control.name }}-os-{{ item }}.{{ virt_env_ospd_format }}
  with_sequence:
    start=1
    end={{ virt_env_ospd_control.vm_count }}
  when: virt_env_ospd_control is defined

- name: Creating QCOW2 file for compute
  command:
    qemu-img create \
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-os-{{ item }}.{{ virt_env_ospd_format }} {{ virt_env_ospd_compute.disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-os-{{ item }}.{{ virt_env_ospd_format }}
  with_sequence:
    start=1
    end={{ virt_env_ospd_compute.vm_count }}
  when: virt_env_ospd_compute is defined

- name: Creating Ceph virtual machines
  virt:
    name={{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-{{ item }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/ceph.xml.j2') }}
  with_sequence:
    start=1
    end={{ virt_env_ospd_ceph.vm_count }}
  when: virt_env_ospd_ceph is defined

- name: Creating controller virtual machines
  virt:
    name={{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_control.name }}-{{ item }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/control.xml.j2') }}
  with_sequence:
    start=1
    end={{ virt_env_ospd_control.vm_count }}
  when: virt_env_ospd_control is defined

- name: Creating compute virtual machines
  virt:
    name={{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_compute.name }}-{{ item }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/compute.xml.j2') }}
  with_sequence:
    start=1
    end={{ virt_env_ospd_compute.vm_count }}
  when: virt_env_ospd_compute is defined

- name: Creating extra QCOW2 file(s) for Ceph
  shell:
    for n in {1..{{ virt_env_ospd_ceph.extra_disk_count }}}; do
    qemu-img create \
    -f {{ item.format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-ceph-extra-${n}-{{ item.name }}.{{ item.format }} {{ item.size }} ;
    virsh attach-disk {{ virt_env_ospd_vm_name }}-{{ virt_env_ospd_ceph.name }}-${n} \
      --source {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_vm_name }}-ceph-extra-${n}-{{ item.name }}.{{ item.format }} \
      --target {{ item.name }} \
      --persistent || true; done
  with_items: "{{ virt_env_ospd_ceph_extra_disk }}"
  when: virt_env_ospd_ceph.extra_disk_count != 0 | int
