---
# file: roles/virt-env-ospd/tasks/install.yml
- name: Copying undercloud.conf to stack's home
  copy:
    src=/usr/share/instack-undercloud/undercloud.conf.sample
    dest=/home/stack/undercloud.conf
    remote_src=yes
    owner=stack
    group=stack

- name: Running openstack undercloud install (grab a coffee)
  command:
    openstack undercloud install
  become: true
  become_user: stack

- name: Installing OSP-d images via Yum (OSP-d 8 only)
  package:
    name=rhosp-director-images
    state=latest
  when: virt_env_ospd_director_version == '8-director' and
        virt_env_ospd_upload_images is defined and
        not virt_env_ospd_upload_images

- name: Downloading OSP-d images from mburns repo (OSP-d 7 only)
  get_url:
    url={{ item }}
    dest=~/images/
  with_items: "{{ virt_env_ospd_images_link }}"
  become: true
  become_user: stack
  when: virt_env_ospd_director_version == '7-director' and
        virt_env_ospd_upload_images is defined and
        not virt_env_ospd_upload_images

- name: Uploading OSP-d images from playbook (OSP-d 7 only)
  copy:
    src=ospd7/{{ item }}
    dest=~/images/
  with_items:
    - deploy-ramdisk-ironic.tar
    - discovery-ramdisk.tar
    - overcloud-full.tar
  become: true
  become_user: stack
  when: virt_env_ospd_director_version == '7-director' and
        virt_env_ospd_upload_images is defined and
        virt_env_ospd_upload_images

- name: Uploading OSP-d images from playbook (OSP-d 8 only)
  copy:
    src=ospd8/{{ item }}
    dest=~/images/
  with_items:
    - ironic-python-agent.tar
    - overcloud-full.tar
  become: true
  become_user: stack
  when: virt_env_ospd_director_version == '8-director' and
        virt_env_ospd_upload_images is defined and
        virt_env_ospd_upload_images

- name: Extracting OSP-d images (OSP-d 8 only)
  unarchive:
    src=/usr/share/rhosp-director-images/{{ item }}
    dest=~/images/
    copy=no
  with_items:
    - ironic-python-agent.tar
    - overcloud-full.tar
  become: true
  become_user: stack
  when: virt_env_ospd_director_version == '8-director' and
        virt_env_ospd_upload_images is defined and
        not virt_env_ospd_upload_images

- name: Extracting OSP-d images (OSP-d 7 only)
  unarchive:
    src=~/images/{{ item }}
    dest=~/images/
    copy=no
  with_items:
    - deploy-ramdisk-ironic.tar
    - discovery-ramdisk.tar
    - overcloud-full.tar
  become: true
  become_user: stack
  when: virt_env_ospd_director_version == '7-director'

- name: Extracting OSP-d images (OSP-d 8 only)
  unarchive:
    src=~/images/{{ item }}
    dest=~/images/
    copy=no
  with_items:
    - ironic-python-agent.tar
    - overcloud-full.tar
  become: true
  become_user: stack
  when: virt_env_ospd_director_version == '8-director' and
        virt_env_ospd_upload_images is defined and
        virt_env_ospd_upload_images

- name: Uploading overcloud images in Glance
  shell:
    source ~/stackrc ; cd ~/images ;
    openstack overcloud image upload
  become: true
  become_user: stack

- name: Updating the DNS for ctlplane network
  shell:
    source ~/stackrc ;
    neutron subnet-update $(neutron subnet-list -F id --quote none -f csv | grep -v id) --dns-nameserver {{ virt_env_ospd_neutron_dns }}
  become: true
  become_user: stack
