---
# file: roles/virt-env-ospd/tasks/prepare.yml
- name: Installing needed packages
  package:
    name={{ item }}
    state=latest
  with_items: "{{ virt_env_ospd_packages }}"

- name: Creating Linux bridge(s) needed
  shell:
    if ! brctl show | grep -q {{ item }}; then brctl addbr {{ item }}; ip l set {{ item }} up; fi
  with_items: "{{ virt_env_ospd_bridges }}"

- name: Generating the Linux bridge(s) config file
  template:
    src=etc/sysconfig/network-scripts/ifcfg-bridge
    dest=/etc/sysconfig/network-scripts/ifcfg-{{ item }}
  with_items: "{{ virt_env_ospd_bridges }}"

- name: Enabling nested for KVM module
  copy:
    src=etc/modprobe.d/kvm_intel.conf
    dest=/etc/modprobe.d/kvm_intel.conf

- name: Reloading module (if no KVM are running)
  shell:
    if ! grep -q Y /sys/module/kvm_intel/parameters/nested; then rmmod kvm_intel; modprobe kvm_intel; fi

- name: Starting tuned service
  service:
    name=tuned
    state=restarted
    enabled=yes

- name: Activating virtual-host tuned profile
  shell:
    if [ $(tuned-adm active | awk '{ print $NF }') != 'virtual-host' ]; then tuned-adm profile virtual-host; fi
  when: virt_env_ospd_tuned is defined and
        virt_env_ospd_tuned
