---
# file: roles/virt-env-ospd/tasks/subcription-undercloud.yml
- name: Unsubscribing and unregistering the server to RHN
  shell:
    /usr/bin/subscription-manager unsubscribe --all;
    /usr/bin/subscription-manager unregister;
    /usr/bin/subscription-manager clean
  when: virt_env_ospd_rhn_unsubscribe is defined and
        virt_env_ospd_rhn_unsubscribe

- name: Registering the server to RHN
  redhat_subscription:
    username={{ rhn_username }}
    password={{ rhn_password }}
    state=present

- name: Subscribing the server to a pool
  shell:
    /usr/bin/subscription-manager subscribe --pool {{ rhn_pool_id }}

- name: Installing rhos-release package
  package:
    name={{ virt_env_ospd_undercloud_rhos_pkg }}
    state=present
