---
# file: roles/virt-env-ospd/tasks/undercloud-vm.yml
- name: Downloading the RHEL guest image from internal repo
  get_url:
    url={{ virt_env_ospd_guest_link }}
    dest={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}

- name: Copying cloud-init ISO to working directory
  copy:
    src=files/{{ virt_env_ospd_cloud_init_name }}
    dest={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_cloud_init_name }}
    owner=qemu
    group=qemu

- name: Creating QCOW2 baking file for the undercloud
  command:
    qemu-img create \
    -b {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_guest_name }}
    -f {{ virt_env_ospd_format }} \
    {{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_undercloud_name }}.{{ virt_env_ospd_format }} {{ virt_env_ospd_undercloud_disk_size }}
    creates={{ virt_env_ospd_dir }}/images/{{ virt_env_ospd_undercloud_name }}.{{ virt_env_ospd_format }}

- virt:
    name={{ virt_env_ospd_undercloud_name }}
    command=status
  register: vm
  ignore_errors: true

- name: Generating random MAC address
  shell:
    od -An -N6 -tx1 /dev/urandom | sed -e 's/^  *//' -e 's/  */:/g' -e 's/:$//' -e 's/^\(.\)[13579bdf]/\10/'
  register: mac
  when: vm.failed is defined and
        vm.failed

- name: Creating undercloud virtual machine
  virt:
    name={{ virt_env_ospd_undercloud_name }}
    command=define
    xml={{ lookup('template', 'etc/libvirt/qemu/undercloud.xml.j2') }}
  when: vm.failed is defined and
        vm.failed

- name: Starting undercloud virtual machine
  virt:
    name={{ virt_env_ospd_undercloud_name }}
    state=running

- name: Getting the DHCP undercloud's address
  shell:
    virsh net-dhcp-leases default | awk '$3 ~ /{{ mac.stdout }}/ { print $5 }'
  until: undercloud_dhcp_ip.stdout_lines | length > 0
  retries: 20
  register: undercloud_dhcp_ip
  when: vm.failed is defined and
        vm.failed

- set_fact:
    ip={{ undercloud_dhcp_ip }}
  when: undercloud_dhcp_ip.changed

- shell:
    mac=$(virsh domiflist {{ virt_env_ospd_undercloud_name }} | awk '$3 ~ /virbr0/ { print $NF }');
    virsh net-dhcp-leases default | awk '$3 ~ /'$mac'/ { print $5 }'
  register: undercloud_dhcp_ip
  when: vm.failed is not defined

- set_fact:
    ip={{ undercloud_dhcp_ip }}
  when: undercloud_dhcp_ip.changed

- name: Adding undercloud to the inventoy (in memory)
  add_host:
    hostname={{ virt_env_ospd_undercloud_name }}
    ansible_host={{ ip.stdout.split('/')[0] }}
    group=undercloud

- name: Waiting for undercloud booting
  wait_for:
    port: 22
    host: "{{ ip.stdout.split('/')[0] }}"
  delegate_to: 127.0.0.1
